apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: prefetch-dependencies
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "image-build, konflux"
spec:
  description: Task that prefetches project dependencies for hermetic build.
  params:
    - description: Configures project packages that will have their dependencies prefetched.
      name: input
    - description: Set prefetch tool log level (debug, info, warning, error)
      name: log-level
      default: "info"
    - description: Pass YAML-formatted config dump.
      name: config-file-content
      default: ""
    - name: sbom-type
      default: spdx
      description: "Select the SBOM format to generate. Valid values: spdx, cyclonedx."
    - name: mode
      description: "Control how input requirement violations are handled: strict (errors) or permissive (warnings)."
      type: string
      default: strict
    - name: caTrustConfigMapName
      type: string
      description: The name of the ConfigMap to read CA bundle data from.
      default: trusted-ca
    - name: caTrustConfigMapKey
      type: string
      description: The name of the key in the ConfigMap that contains the CA bundle data.
      default: ca-bundle.crt
    - name: ACTIVATION_KEY
      default: activation-key
      description: Name of secret which contains subscription activation key
      type: string
  steps:
    - name: prefetch-dependencies
      env:
        - name: KBC_LOG_LEVEL
          value: $(params.log-level)
        - name: WORKSPACE_GIT_BASIC_AUTH_BOUND
          value: $(workspaces.git-basic-auth.bound)
        - name: WORKSPACE_GIT_BASIC_AUTH_PATH
          value: $(workspaces.git-basic-auth.path)
        - name: WORKSPACE_NETRC_BOUND
          value: $(workspaces.netrc.bound)
        - name: WORKSPACE_NETRC_PATH
          value: $(workspaces.netrc.path)
      image: quay.io/redhat-user-workloads/hermeto-tenant/hermeto:on-pr-7eb63898da07533d8e7a541b3117158321e62aa2
      command: ["konflux-build-cli", "prefetch-dependencies"]
      args:
        - --config-file-content
        - $(params.config-file-content)
        - --input
        - $(params.input)
        - --mode
        - $(params.mode)
        - --output
        - "$(workspaces.source.path)/cachi2/output"
        - --sbom-format
        - $(params.sbom-type)
        - --source
        - "$(workspaces.source.path)/source"
      volumeMounts:
        - name: trusted-ca
          mountPath: /mnt/trusted-ca
          readOnly: true
        - mountPath: /activation-key
          name: activation-key
      computeResources:
        limits:
          cpu: "1"
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 3Gi
  workspaces:
    - name: source
      description: Workspace with the source code.
      optional: false
    - name: git-basic-auth
      description: |
        A Workspace containing a .gitconfig and .git-credentials file or username and password.
        These will be copied to the user's home before prefetch is run. Any other files in this
        Workspace are ignored. It is strongly recommended to bind a Secret to this Workspace over
        other volume types.
      optional: true
    - name: netrc
      description: Workspace containing a .netrc file with credentials for HTTP(S) requests.
      optional: true
  volumes:
    - name: activation-key
      secret:
        optional: true
        secretName: $(params.ACTIVATION_KEY)
    - name: trusted-ca
      configMap:
        name: $(params.caTrustConfigMapName)
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        optional: true
